import { Category, Schema } from './';

export const AtomSite_Schema = {
    'aniso_B[1][1]': Schema.float,
    'aniso_B[1][1]_esd': Schema.float,
    'aniso_B[1][2]': Schema.float,
    'aniso_B[1][2]_esd': Schema.float,
    'aniso_B[1][3]': Schema.float,
    'aniso_B[1][3]_esd': Schema.float,
    'aniso_B[2][2]': Schema.float,
    'aniso_B[2][2]_esd': Schema.float,
    'aniso_B[2][3]': Schema.float,
    'aniso_B[2][3]_esd': Schema.float,
    'aniso_B[3][3]': Schema.float,
    'aniso_B[3][3]_esd': Schema.float,
    aniso_ratio: Schema.float,
    'aniso_U[1][1]': Schema.float,
    'aniso_U[1][1]_esd': Schema.float,
    'aniso_U[1][2]': Schema.float,
    'aniso_U[1][2]_esd': Schema.float,
    'aniso_U[1][3]': Schema.float,
    'aniso_U[1][3]_esd': Schema.float,
    'aniso_U[2][2]': Schema.float,
    'aniso_U[2][2]_esd': Schema.float,
    'aniso_U[2][3]': Schema.float,
    'aniso_U[2][3]_esd': Schema.float,
    'aniso_U[3][3]': Schema.float,
    'aniso_U[3][3]_esd': Schema.float,
    attached_hydrogens: Schema.int,
    auth_asym_id: Schema.strM,
    auth_atom_id: Schema.str,
    auth_comp_id: Schema.str,
    auth_seq_id: Schema.int,   /* NOTE: This is actually a str but most softwares hope to get an int here */
    B_equiv_geom_mean: Schema.float,
    B_equiv_geom_mean_esd: Schema.float,
    B_iso_or_equiv: Schema.float,
    B_iso_or_equiv_esd: Schema.float,
    calc_attached_atom: Schema.str,
    calc_flag: Schema.Enum<'d'|'calc'|'c'|'dum'|null>(['d', 'calc', 'c', 'dum', null]),
    Cartn_x: Schema.float,
    Cartn_x_esd: Schema.float,
    Cartn_y: Schema.float,
    Cartn_y_esd: Schema.float,
    Cartn_z: Schema.float,
    Cartn_z_esd: Schema.float,
    chemical_conn_number: Schema.str,
    constraints: Schema.str,
    details: Schema.str,
    disorder_assembly: Schema.str,
    disorder_group: Schema.str,
    footnote_id: Schema.str,
    fract_x: Schema.float,
    fract_x_esd: Schema.float,
    fract_y: Schema.float,
    fract_y_esd: Schema.float,
    fract_z: Schema.float,
    fract_z_esd: Schema.float,
    group_PDB: Schema.Enum<'atom'|'hetatm'|null>(['atom', 'hetatm', null]),
    id: Schema.intM,   /* NOTE: This is actually a strM but most softwares hope to get an int here */
    label_alt_id: Schema.strM,
    label_asym_id: Schema.strM,
    label_atom_id: Schema.strM,
    label_comp_id: Schema.strM,
    label_entity_id: Schema.strM,
    label_seq_id: Schema.intM,
    occupancy: Schema.float,
    occupancy_esd: Schema.float,
    restraints: Schema.str,
    symmetry_multiplicity: Schema.int,
    thermal_displace_type: Schema.Enum<'uani'|'uiso'|'uovl'|'umpe'|'bani'|'biso'|'bovl'|null>(['uani', 'uiso', 'uovl', 'umpe', 'bani', 'biso', 'bovl', null]),
    type_symbol: Schema.strM,
    U_equiv_geom_mean: Schema.float,
    U_equiv_geom_mean_esd: Schema.float,
    U_iso_or_equiv: Schema.float,
    U_iso_or_equiv_esd: Schema.float,
    Wyckoff_symbol: Schema.str,
    pdbx_atom_ambiguity: Schema.str,
    adp_type: Schema.Enum<'uani'|'uiso'|'uovl'|'umpe'|'bani'|'biso'|'bovl'|null>(['uani', 'uiso', 'uovl', 'umpe', 'bani', 'biso', 'bovl', null]),
    refinement_flags: Schema.Enum<'s'|'g'|'r'|'d'|'t'|'u'|'p'|null>(['s', 'g', 'r', 'd', 't', 'u', 'p', null]),
    refinement_flags_adp: Schema.Enum<'t'|'u'|'tu'|null>(['t', 'u', 'tu', null]),
    refinement_flags_occupancy: Schema.Enum<'p'|null>(['p', null]),
    refinement_flags_posn: Schema.Enum<'d'|'g'|'r'|'s'|'dg'|'dr'|'ds'|'gr'|'gs'|'rs'|'dgr'|'dgs'|'drs'|'grs'|'dgrs'|null>(['d', 'g', 'r', 's', 'dg', 'dr', 'ds', 'gr', 'gs', 'rs', 'dgr', 'dgs', 'drs', 'grs', 'dgrs', null]),
    pdbx_auth_alt_id: Schema.str,
    pdbx_PDB_ins_code: Schema.str,
    pdbx_PDB_model_num: Schema.int,
    pdbx_PDB_residue_no: Schema.str,
    pdbx_PDB_residue_name: Schema.str,
    pdbx_PDB_strand_id: Schema.str,
    pdbx_PDB_atom_name: Schema.str,
    pdbx_auth_atom_name: Schema.str,
    pdbx_formal_charge: Schema.int,
    pdbx_auth_comp_id: Schema.str,
    pdbx_auth_asym_id: Schema.str,
    pdbx_auth_seq_id: Schema.str,
    pdbx_tls_group_id: Schema.str,
    pdbx_ncs_dom_id: Schema.str,
    pdbx_struct_group_id: Schema.str,
    pdbx_group_NDB: Schema.str,
    pdbx_atom_group: Schema.str,
    pdbx_label_seq_num: Schema.str,
    pdbx_not_in_asym: Schema.str,
    pdbx_label_index: Schema.int,
    pdbx_sifts_xref_db_name: Schema.str,
    pdbx_sifts_xref_db_acc: Schema.str,
    pdbx_sifts_xref_db_num: Schema.str,
    pdbx_sifts_xref_db_res: Schema.str,
};
export type AtomSite_Schema = typeof AtomSite_Schema;
export const AtomSite: Category<AtomSite_Schema> = {
    name: 'atom_site',
    schema: AtomSite_Schema,
};
