import { Category, Schema } from './';

export const ChemComp_Schema = {
    formula: Schema.str,
    formula_weight: Schema.float,
    id: Schema.strM,
    model_details: Schema.str,
    model_erf: Schema.str,
    model_source: Schema.str,
    mon_nstd_class: Schema.str,
    mon_nstd_details: Schema.str,
    mon_nstd_flag: Schema.Enum<'no'|'n'|'yes'|'y'|null>(['no', 'n', 'yes', 'y', null]),
    mon_nstd_parent: Schema.str,
    mon_nstd_parent_comp_id: Schema.str,
    name: Schema.str,
    number_atoms_all: Schema.int,
    number_atoms_nh: Schema.int,
    one_letter_code: Schema.str,
    three_letter_code: Schema.str,
    type: Schema.Enum<'d-peptide linking'|'l-peptide linking'|'d-peptide nh3 amino terminus'|'l-peptide nh3 amino terminus'|'d-peptide cooh carboxy terminus'|'l-peptide cooh carboxy terminus'|'dna linking'|'rna linking'|'l-rna linking'|'l-dna linking'|'dna oh 5 prime terminus'|'rna oh 5 prime terminus'|'dna oh 3 prime terminus'|'rna oh 3 prime terminus'|'d-saccharide, beta linking'|'d-saccharide, alpha linking'|'l-saccharide, beta linking'|'l-saccharide, alpha linking'|'l-saccharide'|'d-saccharide'|'saccharide'|'non-polymer'|'peptide linking'|'peptide-like'|'l-gamma-peptide, c-delta linking'|'d-gamma-peptide, c-delta linking'|'l-beta-peptide, c-gamma linking'|'d-beta-peptide, c-gamma linking'|'other'>(['d-peptide linking', 'l-peptide linking', 'd-peptide nh3 amino terminus', 'l-peptide nh3 amino terminus', 'd-peptide cooh carboxy terminus', 'l-peptide cooh carboxy terminus', 'dna linking', 'rna linking', 'l-rna linking', 'l-dna linking', 'dna oh 5 prime terminus', 'rna oh 5 prime terminus', 'dna oh 3 prime terminus', 'rna oh 3 prime terminus', 'd-saccharide, beta linking', 'd-saccharide, alpha linking', 'l-saccharide, beta linking', 'l-saccharide, alpha linking', 'l-saccharide', 'd-saccharide', 'saccharide', 'non-polymer', 'peptide linking', 'peptide-like', 'l-gamma-peptide, c-delta linking', 'd-gamma-peptide, c-delta linking', 'l-beta-peptide, c-gamma linking', 'd-beta-peptide, c-gamma linking', 'other']),
    pdbx_synonyms: Schema.str,
    pdbx_modification_details: Schema.str,
    pdbx_component_no: Schema.int,
    pdbx_type: Schema.str,
    pdbx_ambiguous_flag: Schema.str,
    pdbx_replaced_by: Schema.str,
    pdbx_replaces: Schema.str,
    pdbx_formal_charge: Schema.int,
    pdbx_subcomponent_list: Schema.str,
    pdbx_model_coordinates_details: Schema.str,
    pdbx_model_coordinates_db_code: Schema.str,
    pdbx_ideal_coordinates_details: Schema.str,
    pdbx_ideal_coordinates_missing_flag: Schema.Enum<'y'|'n'|null>(['y', 'n', null]),
    pdbx_model_coordinates_missing_flag: Schema.Enum<'y'|'n'|null>(['y', 'n', null]),
    pdbx_initial_date: Schema.date,
    pdbx_modified_date: Schema.date,
    pdbx_release_status: Schema.Enum<'rel'|'hold'|'hpub'|'obs'|'del'|'ref_only'|null>(['rel', 'hold', 'hpub', 'obs', 'del', 'ref_only', null]),
    pdbx_processing_site: Schema.Enum<'pdbe'|'ebi'|'pdbj'|'pdbc'|'rcsb'|null>(['pdbe', 'ebi', 'pdbj', 'pdbc', 'rcsb', null]),
    pdbx_number_subcomponents: Schema.int,
    pdbx_class_1: Schema.str,
    pdbx_class_2: Schema.str,
    pdbx_comp_type: Schema.Enum<'solvent'|'organic ligand'|'inorganic ligand'|'organometalic ligand'|'metal cation'|null>(['solvent', 'organic ligand', 'inorganic ligand', 'organometalic ligand', 'metal cation', null]),
    pdbx_reserved_name: Schema.str,
    pdbx_status: Schema.str,
    pdbx_type_modified: Schema.int,
    pdbx_casnum: Schema.str,
    pdbx_smiles: Schema.str,
    pdbx_nscnum: Schema.str,
};
export type ChemComp_Schema = typeof ChemComp_Schema;
export const ChemComp: Category<ChemComp_Schema> = {
    name: 'chem_comp',
    schema: ChemComp_Schema,
};
