;import { Category, Schema } from './';

export const PdbxDatabaseStatus_Schema = {
    status_code: Schema.Enum<'PROC'|'WAIT'|'REL'|'HOLD'|'HPUB'|'REFI'|'OBS'|'WDRN'|'AUTH'|'POLC'|'REPL'|'AUCO'|'TRSF'|'RMVD'|'DEL'|'REV'|'UPD'|'BIB'>(['PROC', 'WAIT', 'REL', 'HOLD', 'HPUB', 'REFI', 'OBS', 'WDRN', 'AUTH', 'POLC', 'REPL', 'AUCO', 'TRSF', 'RMVD', 'DEL', 'REV', 'UPD', 'BIB']),
    author_release_status_code: Schema.Enum<'REL'|'HOLD'|'HPUB'|'REFI'|'OBS'|'WDRN'>(['REL', 'HOLD', 'HPUB', 'REFI', 'OBS', 'WDRN']),
    status_code_sf: Schema.Enum<'PROC'|'WAIT'|'REL'|'HOLD'|'HPUB'|'OBS'|'WDRN'|'AUTH'|'POLC'|'REPL'|'RMVD'>(['PROC', 'WAIT', 'REL', 'HOLD', 'HPUB', 'OBS', 'WDRN', 'AUTH', 'POLC', 'REPL', 'RMVD']),
    status_code_mr: Schema.Enum<'PROC'|'WAIT'|'REL'|'HOLD'|'HPUB'|'OBS'|'WDRN'|'AUTH'|'POLC'|'REPL'|'AUCO'|'RMVD'>(['PROC', 'WAIT', 'REL', 'HOLD', 'HPUB', 'OBS', 'WDRN', 'AUTH', 'POLC', 'REPL', 'AUCO', 'RMVD']),
    dep_release_code_coordinates: Schema.Enum<'RELEASE NOW'|'HOLD FOR PUBLICATION'|'HOLD FOR 4 WEEKS'|'HOLD FOR 6 WEEKS'|'HOLD FOR 8 WEEKS'|'HOLD FOR 6 MONTHS'|'HOLD FOR 1 YEAR'>(['RELEASE NOW', 'HOLD FOR PUBLICATION', 'HOLD FOR 4 WEEKS', 'HOLD FOR 6 WEEKS', 'HOLD FOR 8 WEEKS', 'HOLD FOR 6 MONTHS', 'HOLD FOR 1 YEAR']),
    dep_release_code_sequence: Schema.Enum<'RELEASE NOW'|'HOLD FOR RELEASE'>(['RELEASE NOW', 'HOLD FOR RELEASE']),
    dep_release_code_struct_fact: Schema.Enum<'RELEASE NOW'|'HOLD FOR PUBLICATION'|'HOLD FOR 4 WEEKS'|'HOLD FOR 8 WEEKS'|'HOLD FOR 6 MONTHS'|'HOLD FOR 1 YEAR'|'HOLD FOR 4 YEARS'>(['RELEASE NOW', 'HOLD FOR PUBLICATION', 'HOLD FOR 4 WEEKS', 'HOLD FOR 8 WEEKS', 'HOLD FOR 6 MONTHS', 'HOLD FOR 1 YEAR', 'HOLD FOR 4 YEARS']),
    dep_release_code_nmr_constraints: Schema.Enum<'RELEASE NOW'|'HOLD FOR PUBLICATION'|'HOLD FOR 4 WEEKS'|'HOLD FOR 6 MONTHS'|'HOLD FOR 1 YEAR'>(['RELEASE NOW', 'HOLD FOR PUBLICATION', 'HOLD FOR 4 WEEKS', 'HOLD FOR 6 MONTHS', 'HOLD FOR 1 YEAR']),
    entry_id: Schema.strM,
    recvd_deposit_form: Schema.str,
    date_deposition_form: Schema.time,
    date_begin_deposition: Schema.time,
    date_begin_processing: Schema.time,
    date_end_processing: Schema.time,
    date_begin_release_preparation: Schema.time,
    date_author_release_request: Schema.time,
    recvd_coordinates: Schema.str,
    date_coordinates: Schema.time,
    recvd_struct_fact: Schema.str,
    date_struct_fact: Schema.time,
    recvd_nmr_constraints: Schema.str,
    date_nmr_constraints: Schema.time,
    recvd_internal_approval: Schema.str,
    recvd_manuscript: Schema.str,
    date_manuscript: Schema.time,
    name_depositor: Schema.str,
    recvd_author_approval: Schema.str,
    author_approval_type: Schema.Enum<'implicit'|'explicit'>(['implicit', 'explicit']),
    date_author_approval: Schema.time,
    recvd_initial_deposition_date: Schema.date,
    date_submitted: Schema.time,
    rcsb_annotator: Schema.str,
    date_of_sf_release: Schema.date,
    date_of_mr_release: Schema.date,
    date_of_PDB_release: Schema.time,
    date_hold_coordinates: Schema.time,
    date_hold_struct_fact: Schema.time,
    date_hold_nmr_constraints: Schema.time,
    hold_for_publication: Schema.str,
    SG_entry: Schema.str,
    pdb_date_of_author_approval: Schema.time,
    deposit_site: Schema.Enum<'NDB'|'RCSB'|'PDBE'|'PDBJ'|'BMRB'|'BNL'|'PDBC'>(['NDB', 'RCSB', 'PDBE', 'PDBJ', 'BMRB', 'BNL', 'PDBC']),
    process_site: Schema.Enum<'NDB'|'RCSB'|'PDBE'|'PDBJ'|'BNL'|'PDBC'>(['NDB', 'RCSB', 'PDBE', 'PDBJ', 'BNL', 'PDBC']),
    dep_release_code_chemical_shifts: Schema.str,
    recvd_chemical_shifts: Schema.str,
    date_chemical_shifts: Schema.time,
    date_hold_chemical_shifts: Schema.time,
    status_code_cs: Schema.Enum<'PROC'|'WAIT'|'AUTH'|'POLC'|'REPL'|'AUCO'|'REL'|'HOLD'|'HPUB'|'OBS'|'RMVD'|'WDRN'>(['PROC', 'WAIT', 'AUTH', 'POLC', 'REPL', 'AUCO', 'REL', 'HOLD', 'HPUB', 'OBS', 'RMVD', 'WDRN']),
    date_of_cs_release: Schema.date,
    date_nmr_data: Schema.time,
    date_hold_nmr_data: Schema.time,
    date_of_nmr_data_release: Schema.date,
    dep_release_code_nmr_data: Schema.Enum<'RELEASE NOW'|'HOLD FOR PUBLICATION'|'HOLD FOR 6 MONTHS'|'HOLD FOR 1 YEAR'>(['RELEASE NOW', 'HOLD FOR PUBLICATION', 'HOLD FOR 6 MONTHS', 'HOLD FOR 1 YEAR']),
    recvd_nmr_data: Schema.str,
    status_code_nmr_data: Schema.Enum<'PROC'|'WAIT'|'AUTH'|'POLC'|'REPL'|'REL'|'HOLD'|'HPUB'|'OBS'|'RMVD'|'WDRN'>(['PROC', 'WAIT', 'AUTH', 'POLC', 'REPL', 'REL', 'HOLD', 'HPUB', 'OBS', 'RMVD', 'WDRN']),
    methods_development_category: Schema.Enum<'CAPRI'|'CASP'|'CASD-NMR'|'FoldIt'|'GPCR Dock'|'D3R'|'RNA-Puzzles'>(['CAPRI', 'CASP', 'CASD-NMR', 'FoldIt', 'GPCR Dock', 'D3R', 'RNA-Puzzles']),
    pdb_format_compatible: Schema.str,
    post_rel_status: Schema.Enum<'PROC'|'WAIT'|'HOLD'|'HPUB'|'OBS'|'WDRN'|'AUTH'|'REPL'|'AUCO'>(['PROC', 'WAIT', 'HOLD', 'HPUB', 'OBS', 'WDRN', 'AUTH', 'REPL', 'AUCO']),
    post_rel_recvd_coord: Schema.Enum<'Y'|'N'>(['Y', 'N']),
    post_rel_recvd_coord_date: Schema.date,
    auth_req_rel_date: Schema.date,
    ndb_tid: Schema.str,
    status_coordinates_in_NDB: Schema.str,
    date_revised: Schema.date,
    replaced_entry_id: Schema.str,
    revision_id: Schema.str,
    revision_description: Schema.str,
    pdbx_annotator: Schema.str,
    date_of_NDB_release: Schema.date,
    date_released_to_PDB: Schema.date,
    skip_PDB_REMARK_500: Schema.str,
    skip_PDB_REMARK: Schema.str,
    title_suppression: Schema.str,
    date_accepted_terms_and_conditions: Schema.date,
};
export type PdbxDatabaseStatus_Schema = typeof PdbxDatabaseStatus_Schema;
export const PdbxDatabaseStatus: Category<PdbxDatabaseStatus_Schema> = {
    name: 'pdbx_database_status',
    schema: PdbxDatabaseStatus_Schema,
};
