import { Category, Schema } from './';

export const PdbxDatabaseStatus_Schema = {
    status_code: Schema.Enum<'proc'|'wait'|'rel'|'hold'|'hpub'|'refi'|'obs'|'wdrn'|'auth'|'polc'|'repl'|'auco'|'trsf'|'rmvd'|'del'|'rev'|'upd'|'bib'>(['proc', 'wait', 'rel', 'hold', 'hpub', 'refi', 'obs', 'wdrn', 'auth', 'polc', 'repl', 'auco', 'trsf', 'rmvd', 'del', 'rev', 'upd', 'bib']),
    author_release_status_code: Schema.Enum<'rel'|'hold'|'hpub'|'refi'|'obs'|'wdrn'|null>(['rel', 'hold', 'hpub', 'refi', 'obs', 'wdrn', null]),
    status_code_sf: Schema.Enum<'proc'|'wait'|'rel'|'hold'|'hpub'|'obs'|'wdrn'|'auth'|'polc'|'repl'|'rmvd'|null>(['proc', 'wait', 'rel', 'hold', 'hpub', 'obs', 'wdrn', 'auth', 'polc', 'repl', 'rmvd', null]),
    status_code_mr: Schema.Enum<'proc'|'wait'|'rel'|'hold'|'hpub'|'obs'|'wdrn'|'auth'|'polc'|'repl'|'auco'|'rmvd'|null>(['proc', 'wait', 'rel', 'hold', 'hpub', 'obs', 'wdrn', 'auth', 'polc', 'repl', 'auco', 'rmvd', null]),
    dep_release_code_coordinates: Schema.Enum<'release now'|'hold for publication'|'hold for 4 weeks'|'hold for 6 weeks'|'hold for 8 weeks'|'hold for 6 months'|'hold for 1 year'|null>(['release now', 'hold for publication', 'hold for 4 weeks', 'hold for 6 weeks', 'hold for 8 weeks', 'hold for 6 months', 'hold for 1 year', null]),
    dep_release_code_sequence: Schema.Enum<'release now'|'hold for release'|null>(['release now', 'hold for release', null]),
    dep_release_code_struct_fact: Schema.Enum<'release now'|'hold for publication'|'hold for 4 weeks'|'hold for 8 weeks'|'hold for 6 months'|'hold for 1 year'|'hold for 4 years'|null>(['release now', 'hold for publication', 'hold for 4 weeks', 'hold for 8 weeks', 'hold for 6 months', 'hold for 1 year', 'hold for 4 years', null]),
    dep_release_code_nmr_constraints: Schema.Enum<'release now'|'hold for publication'|'hold for 4 weeks'|'hold for 6 months'|'hold for 1 year'|null>(['release now', 'hold for publication', 'hold for 4 weeks', 'hold for 6 months', 'hold for 1 year', null]),
    entry_id: Schema.strM,
    recvd_deposit_form: Schema.str,
    date_deposition_form: Schema.time,
    date_begin_deposition: Schema.time,
    date_begin_processing: Schema.time,
    date_end_processing: Schema.time,
    date_begin_release_preparation: Schema.time,
    date_author_release_request: Schema.time,
    recvd_coordinates: Schema.str,
    date_coordinates: Schema.time,
    recvd_struct_fact: Schema.str,
    date_struct_fact: Schema.time,
    recvd_nmr_constraints: Schema.str,
    date_nmr_constraints: Schema.time,
    recvd_internal_approval: Schema.str,
    recvd_manuscript: Schema.str,
    date_manuscript: Schema.time,
    name_depositor: Schema.str,
    recvd_author_approval: Schema.str,
    author_approval_type: Schema.Enum<'implicit'|'explicit'|null>(['implicit', 'explicit', null]),
    date_author_approval: Schema.time,
    recvd_initial_deposition_date: Schema.date,
    date_submitted: Schema.time,
    rcsb_annotator: Schema.str,
    date_of_sf_release: Schema.date,
    date_of_mr_release: Schema.date,
    date_of_PDB_release: Schema.time,
    date_hold_coordinates: Schema.time,
    date_hold_struct_fact: Schema.time,
    date_hold_nmr_constraints: Schema.time,
    hold_for_publication: Schema.str,
    SG_entry: Schema.str,
    pdb_date_of_author_approval: Schema.time,
    deposit_site: Schema.Enum<'ndb'|'rcsb'|'pdbe'|'pdbj'|'bmrb'|'bnl'|'pdbc'|null>(['ndb', 'rcsb', 'pdbe', 'pdbj', 'bmrb', 'bnl', 'pdbc', null]),
    process_site: Schema.Enum<'ndb'|'rcsb'|'pdbe'|'pdbj'|'bnl'|'pdbc'|null>(['ndb', 'rcsb', 'pdbe', 'pdbj', 'bnl', 'pdbc', null]),
    dep_release_code_chemical_shifts: Schema.str,
    recvd_chemical_shifts: Schema.str,
    date_chemical_shifts: Schema.time,
    date_hold_chemical_shifts: Schema.time,
    status_code_cs: Schema.Enum<'proc'|'wait'|'auth'|'polc'|'repl'|'auco'|'rel'|'hold'|'hpub'|'obs'|'rmvd'|'wdrn'|null>(['proc', 'wait', 'auth', 'polc', 'repl', 'auco', 'rel', 'hold', 'hpub', 'obs', 'rmvd', 'wdrn', null]),
    date_of_cs_release: Schema.date,
    date_nmr_data: Schema.time,
    date_hold_nmr_data: Schema.time,
    date_of_nmr_data_release: Schema.date,
    dep_release_code_nmr_data: Schema.Enum<'release now'|'hold for publication'|'hold for 6 months'|'hold for 1 year'|null>(['release now', 'hold for publication', 'hold for 6 months', 'hold for 1 year', null]),
    recvd_nmr_data: Schema.str,
    status_code_nmr_data: Schema.Enum<'proc'|'wait'|'auth'|'polc'|'repl'|'rel'|'hold'|'hpub'|'obs'|'rmvd'|'wdrn'|null>(['proc', 'wait', 'auth', 'polc', 'repl', 'rel', 'hold', 'hpub', 'obs', 'rmvd', 'wdrn', null]),
    methods_development_category: Schema.Enum<'capri'|'casp'|'casd-nmr'|'foldit'|'gpcr dock'|'d3r'|'rna-puzzles'|null>(['capri', 'casp', 'casd-nmr', 'foldit', 'gpcr dock', 'd3r', 'rna-puzzles', null]),
    pdb_format_compatible: Schema.str,
    post_rel_status: Schema.Enum<'proc'|'wait'|'hold'|'hpub'|'obs'|'wdrn'|'auth'|'repl'|'auco'|null>(['proc', 'wait', 'hold', 'hpub', 'obs', 'wdrn', 'auth', 'repl', 'auco', null]),
    post_rel_recvd_coord: Schema.Enum<'y'|'n'|null>(['y', 'n', null]),
    post_rel_recvd_coord_date: Schema.date,
    auth_req_rel_date: Schema.date,
    ndb_tid: Schema.str,
    status_coordinates_in_NDB: Schema.str,
    date_revised: Schema.date,
    replaced_entry_id: Schema.str,
    revision_id: Schema.str,
    revision_description: Schema.str,
    pdbx_annotator: Schema.str,
    date_of_NDB_release: Schema.date,
    date_released_to_PDB: Schema.date,
    skip_PDB_REMARK_500: Schema.str,
    skip_PDB_REMARK: Schema.str,
    title_suppression: Schema.str,
    date_accepted_terms_and_conditions: Schema.date,
};
export type PdbxDatabaseStatus_Schema = typeof PdbxDatabaseStatus_Schema;
export const PdbxDatabaseStatus: Category<PdbxDatabaseStatus_Schema> = {
    name: 'pdbx_database_status',
    schema: PdbxDatabaseStatus_Schema,
};
