import { ElementaryResidue } from './';
import { shiftedName } from './atoms';

export type Triplet = [a: string, b: string, c: string];

const Adenine = [
    ["C1'", "C2'", "C3'"],
    ["C1'", "N9", "C4"],
    ["C1'", "N9", "C8"],
    ["C2", "N1", "C6"],
    ["C2'", "C1'", "N9"],
    ["C2'", "C3'", "C4'"],
    ["C3'", "C4'", "O4'"],
    ["C4", "C5", "N7"],
    ["C4", "N3", "C2"],
    ["C4'", "C3'", "O3'"],
    ["C4'", "O4'", "C1'"],
    ["C5", "N7", "C8"],
    ["C5'", "C4'", "C3'"],
    ["C6", "C5", "C4"],
    ["C6", "C5", "N7"],
    ["C8", "N9", "C4"],
    ["N1", "C6", "C5"],
    ["N1", "C6", "N6"],
    ["N3", "C2", "N1"],
    ["N3", "C4", "C5"],
    ["N6", "C6", "C5"],
    ["N7", "C8", "N9"],
    ["N9", "C4", "C5"],
    ["N9", "C4", "N3"],
    [shiftedName("O3'", -1), "P", "O5'"],
    [shiftedName("O3'", -1), "P", "OP1"],
    [shiftedName("O3'", -1), "P", "OP2"],
    ["O4'", "C1'", "C2'"],
    ["O4'", "C1'", "N9"],
    ["O5'", "C5'", "C4'"],
    ["OP1", "P", "OP2"],
    ["P", "O5'", "C5'"],
    [shiftedName("C3'", -1), shiftedName("O3'", -1), "P"],
] as Triplet[];

const Cytidine = [
    ["C1'", "C2'", "C3'"],
    ["C1'", "N1", "C2"],
    ["C1'", "N1", "C6"],
    ["C2", "N3", "C4"],
    ["C2'", "C1'", "N1"],
    ["C2'", "C3'", "C4'"],
    ["C3'", "C4'", "O4'"],
    ["C4", "C5", "C6"],
    ["C4'", "C3'", "O3'"],
    ["C4'", "O4'", "C1'"],
    ["C5", "C6", "N1"],
    ["C5'", "C4'", "C3'"],
    ["C6", "N1", "C2"],
    ["N1", "C2", "N3"],
    ["N1", "C2", "O2"],
    ["N3", "C4", "C5"],
    ["N3", "C4", "N4"],
    ["N4", "C4", "C5"],
    ["O2", "C2", "N3"],
    [shiftedName("O3'", -1), "P", "O5'"],
    [shiftedName("O3'", -1), "P", "OP1"],
    [shiftedName("O3'", -1), "P", "OP2"],
    ["O4'", "C1'", "C2'"],
    ["O4'", "C1'", "N1"],
    ["O5'", "C5'", "C4'"],
    ["OP1", "P", "OP2"],
    ["P", "O5'", "C5'"],
    [shiftedName("C3'", -1), shiftedName("O3'", -1), "P"],
] as Triplet[];

const Guanosine = [
    ["C1'", "C2'", "C3'"],
    ["C1'", "N9", "C4"],
    ["C1'", "N9", "C8"],
    ["C2", "N1", "C6"],
    ["C2'", "C1'", "N9"],
    ["C2'", "C3'", "C4'"],
    ["C3'", "C4'", "O4'"],
    ["C4", "C5", "N7"],
    ["C4", "N3", "C2"],
    ["C4'", "C3'", "O3'"],
    ["C4'", "O4'", "C1'"],
    ["C5", "N7", "C8"],
    ["C5'", "C4'", "C3'"],
    ["C6", "C5", "C4"],
    ["C6", "C5", "N7"],
    ["C8", "N9", "C4"],
    ["N1", "C6", "C5"],
    ["N1", "C6", "O6"],
    ["N2", "C2", "N1"],
    ["N3", "C2", "N1"],
    ["N3", "C2", "N2"],
    ["N3", "C4", "C5"],
    ["N7", "C8", "N9"],
    ["N9", "C4", "C5"],
    ["N9", "C4", "N3"],
    [shiftedName("O3'", -1), "P", "O5'"],
    [shiftedName("O3'", -1), "P", "OP1"],
    [shiftedName("O3'", -1), "P", "OP2"],
    ["O4'", "C1'", "C2'"],
    ["O4'", "C1'", "N9"],
    ["O5'", "C5'", "C4'"],
    ["O6", "C6", "C5"],
    ["OP1", "P", "OP2"],
    ["P", "O5'", "C5'"],
    [shiftedName("C3'", -1), shiftedName("O3'", -1), "P"],
] as Triplet[];

const Uracil = [
    ["C1'", "C2'", "C3'"],
    ["C1'", "N1", "C2"],
    ["C1'", "N1", "C6"],
    ["C2", "N3", "C4"],
    ["C2'", "C1'", "N1"],
    ["C2'", "C3'", "C4'"],
    ["C3'", "C4'", "O4'"],
    ["C4", "C5", "C6"],
    ["C4'", "C3'", "O3'"],
    ["C4'", "O4'", "C1'"],
    ["C5", "C6", "N1"],
    ["C5'", "C4'", "C3'"],
    ["C6", "N1", "C2"],
    ["N1", "C2", "N3"],
    ["N1", "C2", "O2"],
    ["N3", "C4", "C5"],
    ["N3", "C4", "O4"],
    ["O2", "C2", "N3"],
    [shiftedName("O3'", -1), "P", "O5'"],
    [shiftedName("O3'", -1), "P", "OP1"],
    [shiftedName("O3'", -1), "P", "OP2"],
    ["O4", "C4", "C5"],
    ["O4'", "C1'", "C2'"],
    ["O4'", "C1'", "N1"],
    ["O5'", "C5'", "C4'"],
    ["OP1", "P", "OP2"],
    ["P", "O5'", "C5'"],
    [shiftedName("C3'", -1), shiftedName("O3'", -1), "P"],
] as Triplet[];

const Thymine = [
    ["C1'", "C2'", "C3'"],
    ["C1'", "N1", "C2"],
    ["C1'", "N1", "C6"],
    ["C2", "N3", "C4"],
    ["C2'", "C1'", "N1"],
    ["C2'", "C3'", "C4'"],
    ["C3'", "C4'", "O4'"],
    ["C4", "C5", "C6"],
    ["C4", "C5", "C7"],
    ["C4'", "C3'", "O3'"],
    ["C4'", "O4'", "C1'"],
    ["C5", "C6", "N1"],
    ["C5'", "C4'", "C3'"],
    ["C6", "N1", "C2"],
    ["C7", "C5", "C6"],
    ["N1", "C2", "N3"],
    ["N1", "C2", "O2"],
    ["N3", "C4", "C5"],
    ["N3", "C4", "O4"],
    ["O2", "C2", "N3"],
    [shiftedName("O3'", -1), "P", "O5'"],
    [shiftedName("O3'", -1), "P", "OP1"],
    [shiftedName("O3'", -1), "P", "OP2"],
    ["O4", "C4", "C5"],
    ["O4'", "C1'", "C2'"],
    ["O4'", "C1'", "N1"],
    ["O5'", "C5'", "C4'"],
    ["OP1", "P", "OP2"],
    ["P", "O5'", "C5'"],
    [shiftedName("C3'", -1), shiftedName("O3'", -1), "P"],
] as Triplet[];

export const Angles: Record<ElementaryResidue, Triplet[]> = {
    'A': Adenine,
    'DA': Adenine,
    'C': Cytidine,
    'DC': Cytidine,
    'G': Guanosine,
    'DG': Guanosine,
    'DT': Thymine,
    'U': Uracil,
    'DU': Uracil,
} as const;

export function tripletTag(t: Triplet) {
    return t.join('^');
}
