import { shiftedName } from './atoms';
import { Residues } from '../residues';

export type Pair = [a: string, b: string];

const Adenine = [
    ["C1'", "C2'"],
    ["C1'", "N9"],
    ["C2", "N1"],
    ["C2'", "C3'"],
    ["C3'", "O3'"],
    ["C4", "C5"],
    ["C4", "N3"],
    ["C4'", "C3'"],
    ["C4'", "O4'"],
    ["C5", "N7"],
    ["C5'", "C4'"],
    ["C6", "C5"],
    ["C6", "N6"],
    ["C8", "N9"],
    ["N1", "C6"],
    ["N3", "C2"],
    ["N7", "C8"],
    ["N9", "C4"],
    ["O4'", "C1'"],
    ["O5'", "C5'"],
    ["P", "O5'"],
    ["P", "OP1"],
    ["P", "OP2"],
    [shiftedName("O3'", -1), "P"],
] as Pair[];

const Cytidine = [
    ["C1'", "C2'"],
    ["C1'", "N1"],
    ["C2", "N3"],
    ["C2", "O2"],
    ["C2'", "C3'"],
    ["C3'", "O3'"],
    ["C4", "C5"],
    ["C4", "N4"],
    ["C4'", "C3'"],
    ["C4'", "O4'"],
    ["C5", "C6"],
    ["C5'", "C4'"],
    ["C6", "N1"],
    ["N1", "C2"],
    ["N3", "C4"],
    ["O4'", "C1'"],
    ["O5'", "C5'"],
    ["P", "O5'"],
    ["P", "OP1"],
    ["P", "OP2"],
    [shiftedName("O3'", -1), "P"],
] as Pair[];

const Guanosine = [
    ["C1'", "C2'"],
    ["C1'", "N9"],
    ["C2", "N1"],
    ["C2", "N2"],
    ["C2'", "C3'"],
    ["C3'", "O3'"],
    ["C4", "C5"],
    ["C4", "N3"],
    ["C4'", "C3'"],
    ["C4'", "O4'"],
    ["C5", "N7"],
    ["C5'", "C4'"],
    ["C6", "C5"],
    ["C6", "O6"],
    ["C8", "N9"],
    ["N1", "C6"],
    ["N3", "C2"],
    ["N7", "C8"],
    ["N9", "C4"],
    ["O4'", "C1'"],
    ["O5'", "C5'"],
    ["P", "O5'"],
    ["P", "OP1"],
    ["P", "OP2"],
    [shiftedName("O3'", -1), "P"],
] as Pair[];

const Uracil = [
    ["C1'", "C2'"],
    ["C1'", "N1"],
    ["C2", "N3"],
    ["C2", "O2"],
    ["C2'", "C3'"],
    ["C3'", "O3'"],
    ["C4", "C5"],
    ["C4", "O4"],
    ["C4'", "C3'"],
    ["C4'", "O4'"],
    ["C5", "C6"],
    ["C5'", "C4'"],
    ["C6", "N1"],
    ["N1", "C2"],
    ["N3", "C4"],
    ["O4'", "C1'"],
    ["O5'", "C5'"],
    ["P", "O5'"],
    ["P", "OP1"],
    ["P", "OP2"],
    [shiftedName("O3'", -1), "P"],
] as Pair[];

const Thymine = [
    ["C1'", "C2'"],
    ["C1'", "N1"],
    ["C2", "N3"],
    ["C2", "O2"],
    ["C2'", "C3'"],
    ["C3'", "O3'"],
    ["C4", "C5"],
    ["C4", "O4"],
    ["C4'", "C3'"],
    ["C4'", "O4'"],
    ["C5", "C6"],
    ["C5", "C7"],
    ["C5'", "C4'"],
    ["C6", "N1"],
    ["N1", "C2"],
    ["N3", "C4"],
    ["O4'", "C1'"],
    ["O5'", "C5'"],
    ["P", "O5'"],
    ["P", "OP1"],
    ["P", "OP2"],
    [shiftedName("O3'", -1), "P"],
] as Pair[];

export const Lengths: Record<Residues.ElementaryResidue, Pair[]> = {
    'A': Adenine,
    'DA': Adenine,
    'C': Cytidine,
    'DC': Cytidine,
    'G': Guanosine,
    'DG': Guanosine,
    'DT': Thymine,
    'U': Uracil,
};

export function pairTag(p: Pair) {
    return p.join('^');
}
