import * as React from 'react';
import { View } from '../view';

export class HelpRefinement extends View {
        render() {
            return (
                <div>
                    <h2 className='font-din-2014 font-700 text-20px mb-2'>Refinement</h2>
                    <div className='font-din-2014 text-16px mb-2'>
                        The refinement page is still being developed to help users refine their structures using NtC conformers. It provides tools for modifying the automatically assigned NtCs and inspecting the changes visually and through similarity and connectivity plots. The user can create multiple sets of modified NtCs to further refine the structure. The default set, called “(Computed)”, cannot be modified and contains NtCs assigned automatically by DNATCO.
                    </div>
                    <h3 className='font-din-2014 font-700 text-18px mb-2'>Connectivity Plot tab</h3>
                    <div className='font-din-2014 text-16px mb-2'>
                        The Connectivity Plot tab displays three different plots - the similarity plot, which is also available in validation mode, and two connectivity plots. The connectivity plots show how well-connected the structure would be if the parts of the structure that make up the previous, currently selected, and next steps were all replaced by reference NtCs. To calculate connectivity to the previous step, DNATCO uses the positions of the C5’ and O3’ atoms of the first residue of the currently selected step and the positions of the C5’ and O3’ atoms of the second residue of the previous step. The distances between both C5’ and O3’ atoms are plotted in the connectivity plot. Connectivity to the next step is calculated similarly, but it uses distances between the C5’/O3’ atoms of the second residue of the currently selected step and the C5’/O3’ atoms of the first residue of the next step. DNATCO calculates connectivities between the currently selected NtC of the current step and all reference NtCs applied to the previous and next steps.
                    </div>
                    <h3 className='font-din-2014 font-700 text-18px mb-2'>Restraints</h3>
                    <div className='font-din-2014 text-16px mb-2'>
                        The REFMAC Restraints tab provides a list of restraints that can be supplied to the REFMAC software. These restraints are derived from the currently selected set of NtCs. The Phenix Restraints tab is similar to the REFMAC restraints page but provides a set of restraints for the Phenix software. Note that the restraints file generated by DNATCO requires a modified version of Phenix. The MMB Commands File tab provides a snippet of a commands file for the MacroMolecule Builder (MMB) software. Adding this snippet to an MMB commands file allows MMB to attempt to force the structure geometry into the prescribed NtCs. The Change NtCs tab is a utility tab for directly modifying the assigned NtCs.
                    </div>
                </div>
            );
        }
    }

export namespace HelpRefinement {
    export const StepSwitcher = () => {}
}