export namespace Residues {
    export type ResidueKind = 'purine' | 'pyrimidine' | 'non-standard';

    export function isElementaryResidue(name: string) {
        return ElementaryDNAResidues.has(name) || ElementaryRNAResidues.has(name);
    }

    export function isNucleicResidue(name: string) {
        return StandardResidues.has(name);
        // TODO: Add non-standard residues
    }

    export function isDNAResidue(name: string) {
        return ElementaryDNAResidues.has(name);
    }

    export function isRNAResidue(name: string) {
        return ElementaryRNAResidues.has(name);
    }

    export const ElementaryDNAResidues = new Set<string>([ 'DA', 'DC', 'DG', 'DT' ]);
    export const ElementaryRNAResidues = new Set<string>([ 'A', 'C', 'G', 'U' ]);

    export const StandardResidues = new Set<string>([
         '0A',
        '0AD',
        '0AP',
        '0AV',
         '0C',
        '0DA',
        '0DC',
        '0DG',
        '0DT',
         '0G',
        '0SP',
        '0UH',
        '10C',
        '125',
        '126',
        '127',
        '12A',
        '16B',
        '18M',
        '18Q',
        '1AP',
        '1CC',
        '1DP',
        '1FC',
        '1MA',
        '1MG',
        '1SC',
        '1TW',
        '1WA',
        '2AT',
        '2AU',
        '2BD',
        '2BT',
        '2BU',
        '2EG',
        '2FE',
        '2FI',
        '2GF',
        '2GT',
        '2IA',
        '2JU',
        '2MA',
        '2MG',
        '2MU',
        '2NT',
        '2OT',
        '2PR',
        '2SG',
        '3ME',
        '3ZO',
        '45A',
        '47C',
        '4AC',
        '4DU',
        '4E9',
        '4OC',
        '4PC',
        '4PD',
        '4PE',
        '4SU',
        '4U3',
        '574',
        '5BU',
        '5CF',
        '5CM',
        '5DB',
        '5EJ',
        '5FC',
        '5FU',
        '5HC',
        '5HM',
        '5HU',
        '5IT',
        '5IU',
        '5JO',
        '5MC',
        '5MU',
        '5OC',
        '5PC',
        '5PY',
        '5SE',
        '63G',
        '63H',
        '6FC',
        '6HB',
        '6IA',
        '6MA',
        '6MC',
        '6MT',
        '6MZ',
        '6NW',
        '6OG',
        '6OO',
        '6PO',
        '70U',
        '73W',
        '75B',
        '77Y',
        '7BG',
        '7DA',
        '7GU',
        '7OK',
        '7S3',
        '85Y',
        '8AH',
        '8BA',
        '8DT',
        '8OG',
        '8Y9',
        '92F',
        '94O',
        '9QV',
        '9SI',
        '9SY',
          'A',
        'A23',
        'A2L',
        'A2M',
        'A34',
        'A35',
        'A40',
        'A44',
        'A47',
        'A5L',
        'A5M',
        'A5O',
        'A9Z',
        'ABR',
        'ABS',
        'AET',
        'AF2',
        'AFG',
        'AP7',
         'AS',
        'ATL',
        'AVC',
        'AWC',
        'B7C',
        'B8T',
        'B8W',
        'B9B',
        'BMP',
        'BOE',
        'BRU',
        'BT5',
        'BVP',
          'C',
        'C25',
        'C2L',
        'C2S',
        'C31',
        'C32',
        'C34',
        'C37',
        'C38',
        'C43',
        'C45',
        'C46',
        'C5L',
        'C6G',
        'C7R',
        'C7S',
        'CBR',
        'CBV',
        'CCC',
        'CFL',
        'CFZ',
        'CG1',
        'CM0',
        'CMR',
        'CNU',
        'CSL',
        'CX2',
        'D00',
         'DA',
         'DC',
        'DCG',
        'DDN',
        'DFG',
         'DG',
        'DG8',
        'DHU',
         'DI',
        'DJF',
        'DNR',
         'DP',
         'DT',
         'DU',
        'DUZ',
         'DX',
        'DZM',
          'E',
        'E1X',
        'E6G',
        'EDI',
        'EHG',
        'EIT',
        'EQ0',
        'EWC',
        'F3O',
        'F74',
        'FA5',
        'FDG',
        'FMG',
        'FMU',
        'FNU',
          'G',
        'G25',
        'G2L',
        'G2S',
        'G32',
        'G33',
        'G35',
        'G36',
        'G42',
        'G46',
        'G47',
        'G48',
        'G49',
        'GAO',
        'GCK',
        'GF2',
        'GFL',
        'GMS',
        'GMU',
        'GNE',
        'GOM',
        'GRB',
         'GS',
        'GSR',
        'GSS',
        'GX1',
        'H2U',
        'HEU',
        'HN0',
        'HN1',
          'I',
        'I4U',
        'I5C',
         'IG',
        'IGU',
         'IU',
        'J0X',
        'JDT',
        'JW5',
        'KAG',
        'LCA',
        'LCG',
        'LCH',
        'LGP',
        'LHH',
        'LSH',
        'LST',
        'LV2',
        'M1G',
        'M2G',
        'M3O',
        'M5M',
        'M7A',
        'MA6',
        'MA7',
        'MAD',
        'MDV',
        'MG1',
        'MGV',
        'MIA',
        'MMX',
        'MNU',
        'MRG',
        'MUM',
        'N4S',
        'N5M',
        'N7X',
        'NCX',
        'NDU',
        'NMS',
        'NMT',
        'O2G',
        'O2Z',
        'OFC',
        'OGX',
        'OHU',
        'OIP',
        'OKN',
        'OKT',
        'OMC',
        'OMG',
        'OMU',
        'OWR',
          'P',
        'P2T',
        'P4U',
        'P5P',
        'PDU',
        'PG7',
        'PGN',
        'PGP',
        'PPW',
        'PR5',
        'PRN',
        'PST',
        'PYO',
        'QSK',
        'QSQ',
        'QUO',
          'R',
        'RBD',
        'RDG',
        'RFJ',
        'RMP',
        'RPC',
        'RSP',
        'RSQ',
         'RT',
        'RUS',
         'RY',
        'S2M',
        'S4U',
        'S6G',
        'S6M',
         'SC',
        'SDE',
        'SDG',
        'SDH',
        'SMP',
        'SMT',
        'SRA',
        'SSU',
        'SUR',
          'T',
        'T0N',
        'T0Q',
        'T2S',
        'T31',
        'T36',
        'T38',
        'T39',
        'T41',
        'T5O',
        'T5S',
        'T6A',
        'TAF',
        'TC1',
        'TED',
        'TFE',
        'THX',
         'TS',
        'TTI',
        'TTM',
        'TX2',
          'U',
        'U25',
        'U2L',
        'U2N',
        'U31',
        'U37',
        'U48',
        'U7B',
        'U8U',
        'UAR',
        'UBI',
        'UBR',
        'UCL',
        'UD5',
        'UFB',
        'UFP',
        'UFR',
        'UOA',
        'UPE',
        'UPS',
        'UPV',
        'US2',
        'US3',
        'US5',
        'UY4',
        'V3L',
        'VC7',
          'X',
        'XCY',
        'XFC',
        'XNY',
        'XPB',
        'XUA',
          'Y',
        'Y5P',
        'YCO',
         'YG',
        'YYG',
          'Z',
        'ZDU'
    ]);

    export const StandardResidueKinds = new Map<string, ResidueKind>([
        [  '0A', 'purine' ],
        [ '0AD', 'purine' ],
        [ '0AP', 'pyrimidine' ],
        [ '0AV', 'purine' ],
        [  '0C', 'pyrimidine' ],
        [ '0DA', 'purine' ],
        [ '0DC', 'pyrimidine' ],
        [ '0DG', 'purine' ],
        [ '0DT', 'pyrimidine' ],
        [  '0G', 'purine' ],
        [ '0SP', 'purine' ],
        [ '0UH', 'purine' ],
        [ '10C', 'pyrimidine' ],
        [ '125', 'pyrimidine' ],
        [ '126', 'pyrimidine' ],
        [ '127', 'pyrimidine' ],
        [ '12A', 'purine' ],
        [ '16B', 'pyrimidine' ],
        [ '18M', 'purine' ],
        [ '18Q', 'pyrimidine' ],
        [ '1AP', 'purine' ],
        [ '1CC', 'pyrimidine' ],
        [ '1DP', 'purine' ],
        [ '1FC', 'pyrimidine' ],
        [ '1MA', 'purine' ],
        [ '1MG', 'purine' ],
        [ '1SC', 'pyrimidine' ],
        [ '1TW', 'purine' ],
        [ '1WA', 'purine' ],
        [ '2AT', 'pyrimidine' ],
        [ '2AU', 'pyrimidine' ],
        [ '2BD', 'purine' ],
        [ '2BT', 'pyrimidine' ],
        [ '2BU', 'purine' ],
        [ '2EG', 'purine' ],
        [ '2FE', 'purine' ],
        [ '2FI', 'purine' ],
        [ '2GF', 'pyrimidine' ],
        [ '2GT', 'pyrimidine' ],
        [ '2IA', 'purine' ],
        [ '2JU', 'pyrimidine' ],
        [ '2MA', 'purine' ],
        [ '2MG', 'purine' ],
        [ '2MU', 'pyrimidine' ],
        [ '2NT', 'pyrimidine' ],
        [ '2OT', 'pyrimidine' ],
        [ '2PR', 'purine' ],
        [ '2SG', 'purine' ],
        [ '3ME', 'pyrimidine' ],
        [ '3ZO', 'purine' ],
        [ '45A', 'purine' ],
        [ '47C', 'pyrimidine' ],
        [ '4AC', 'pyrimidine' ],
        [ '4DU', 'purine' ],
        [ '4E9', 'purine' ],
        [ '4OC', 'pyrimidine' ],
        [ '4PC', 'pyrimidine' ],
        [ '4PD', 'pyrimidine' ],
        [ '4PE', 'pyrimidine' ],
        [ '4SU', 'pyrimidine' ],
        [ '4U3', 'pyrimidine' ],
        [ '574', 'purine' ],
        [ '5BU', 'pyrimidine' ],
        [ '5CF', 'pyrimidine' ],
        [ '5CM', 'pyrimidine' ],
        [ '5DB', 'pyrimidine' ],
        [ '5EJ', 'pyrimidine' ],
        [ '5FC', 'pyrimidine' ],
        [ '5FU', 'pyrimidine' ],
        [ '5HC', 'pyrimidine' ],
        [ '5HM', 'pyrimidine' ],
        [ '5HU', 'pyrimidine' ],
        [ '5IT', 'pyrimidine' ],
        [ '5IU', 'pyrimidine' ],
        [ '5JO', 'purine' ],
        [ '5MC', 'pyrimidine' ],
        [ '5MU', 'pyrimidine' ],
        [ '5OC', 'pyrimidine' ],
        [ '5PC', 'pyrimidine' ],
        [ '5PY', 'pyrimidine' ],
        [ '5SE', 'pyrimidine' ],
        [ '63G', 'purine' ],
        [ '63H', 'purine' ],
        [ '6FC', 'pyrimidine' ],
        [ '6HB', 'purine' ],
        [ '6IA', 'purine' ],
        [ '6MA', 'purine' ],
        [ '6MC', 'purine' ],
        [ '6MT', 'purine' ],
        [ '6MZ', 'purine' ],
        [ '6NW', 'purine' ],
        [ '6OG', 'purine' ],
        [ '6OO', 'pyrimidine' ],
        [ '6PO', 'purine' ],
        [ '70U', 'pyrimidine' ],
        [ '73W', 'pyrimidine' ],
        [ '75B', 'pyrimidine' ],
        [ '77Y', 'pyrimidine' ],
        [ '7BG', 'purine' ],
        [ '7DA', 'purine' ],
        [ '7GU', 'purine' ],
        [ '7OK', 'pyrimidine' ],
        [ '7S3', 'purine' ],
        [ '85Y', 'pyrimidine' ],
        [ '8AH', 'purine' ],
        [ '8BA', 'purine' ],
        [ '8DT', 'pyrimidine' ],
        [ '8OG', 'purine' ],
        [ '8Y9', 'purine' ],
        [ '92F', 'pyrimidine' ],
        [ '94O', 'pyrimidine' ],
        [ '9QV', 'pyrimidine' ],
        [ '9SI', 'purine' ],
        [ '9SY', 'purine' ],
        [   'A', 'purine' ],
        [ 'A23', 'purine' ],
        [ 'A2L', 'purine' ],
        [ 'A2M', 'purine' ],
        [ 'A34', 'purine' ],
        [ 'A35', 'purine' ],
        [ 'A40', 'purine' ],
        [ 'A44', 'purine' ],
        [ 'A47', 'purine' ],
        [ 'A5L', 'purine' ],
        [ 'A5M', 'pyrimidine' ],
        [ 'A5O', 'purine' ],
        [ 'A9Z', 'purine' ],
        [ 'ABR', 'purine' ],
        [ 'ABS', 'purine' ],
        [ 'AET', 'purine' ],
        [ 'AF2', 'purine' ],
        [ 'AFG', 'purine' ],
        [ 'AP7', 'purine' ],
        [  'AS', 'purine' ],
        [ 'ATL', 'pyrimidine' ],
        [ 'AVC', 'purine' ],
        [ 'AWC', 'pyrimidine' ],
        [ 'B7C', 'pyrimidine' ],
        [ 'B8T', 'pyrimidine' ],
        [ 'B8W', 'purine' ],
        [ 'B9B', 'purine' ],
        [ 'BMP', 'pyrimidine' ],
        [ 'BOE', 'pyrimidine' ],
        [ 'BRU', 'pyrimidine' ],
        [ 'BT5', 'purine' ],
        [ 'BVP', 'pyrimidine' ],
        [   'C', 'pyrimidine' ],
        [ 'C25', 'pyrimidine' ],
        [ 'C2L', 'pyrimidine' ],
        [ 'C2S', 'pyrimidine' ],
        [ 'C31', 'pyrimidine' ],
        [ 'C32', 'pyrimidine' ],
        [ 'C34', 'pyrimidine' ],
        [ 'C37', 'pyrimidine' ],
        [ 'C38', 'pyrimidine' ],
        [ 'C43', 'pyrimidine' ],
        [ 'C45', 'pyrimidine' ],
        [ 'C46', 'pyrimidine' ],
        [ 'C5L', 'pyrimidine' ],
        [ 'C6G', 'purine' ],
        [ 'C7R', 'pyrimidine' ],
        [ 'C7S', 'pyrimidine' ],
        [ 'CBR', 'pyrimidine' ],
        [ 'CBV', 'pyrimidine' ],
        [ 'CCC', 'pyrimidine' ],
        [ 'CFL', 'pyrimidine' ],
        [ 'CFZ', 'pyrimidine' ],
        [ 'CG1', 'purine' ],
        [ 'CM0', 'pyrimidine' ],
        [ 'CMR', 'pyrimidine' ],
        [ 'CNU', 'pyrimidine' ],
        [ 'CSL', 'pyrimidine' ],
        [ 'CX2', 'pyrimidine' ],
        [ 'D00', 'pyrimidine' ],
        [  'DA', 'purine' ],
        [  'DC', 'pyrimidine' ],
        [ 'DCG', 'purine' ],
        [ 'DDN', 'pyrimidine' ],
        [ 'DFG', 'purine' ],
        [  'DG', 'purine' ],
        [ 'DG8', 'purine' ],
        [ 'DHU', 'pyrimidine' ],
        [  'DI', 'purine' ],
        [ 'DJF', 'purine' ],
        [ 'DNR', 'pyrimidine' ],
        [  'DP', 'purine' ],
        [  'DT', 'pyrimidine' ],
        [  'DU', 'pyrimidine' ],
        [ 'DUZ', 'pyrimidine' ],
        [  'DX', 'purine' ],
        [ 'DZM', 'purine' ],
        [   'E', 'purine' ],
        [ 'E1X', 'purine' ],
        [ 'E6G', 'purine' ],
        [ 'EDI', 'purine' ],
        [ 'EHG', 'purine' ],
        [ 'EIT', 'pyrimidine' ],
        [ 'EQ0', 'purine' ],
        [ 'EWC', 'purine' ],
        [ 'F3O', 'purine' ],
        [ 'F74', 'purine' ],
        [ 'FA5', 'purine' ],
        [ 'FDG', 'purine' ],
        [ 'FMG', 'purine' ],
        [ 'FMU', 'pyrimidine' ],
        [ 'FNU', 'pyrimidine' ],
        [   'G', 'purine' ],
        [ 'G25', 'purine' ],
        [ 'G2L', 'purine' ],
        [ 'G2S', 'purine' ],
        [ 'G32', 'purine' ],
        [ 'G33', 'purine' ],
        [ 'G35', 'purine' ],
        [ 'G36', 'purine' ],
        [ 'G42', 'purine' ],
        [ 'G46', 'purine' ],
        [ 'G47', 'purine' ],
        [ 'G48', 'purine' ],
        [ 'G49', 'purine' ],
        [ 'GAO', 'purine' ],
        [ 'GCK', 'pyrimidine' ],
        [ 'GF2', 'purine' ],
        [ 'GFL', 'purine' ],
        [ 'GMS', 'purine' ],
        [ 'GMU', 'pyrimidine' ],
        [ 'GNE', 'purine' ],
        [ 'GOM', 'purine' ],
        [ 'GRB', 'purine' ],
        [  'GS', 'purine' ],
        [ 'GSR', 'purine' ],
        [ 'GSS', 'purine' ],
        [ 'GX1', 'purine' ],
        [ 'H2U', 'pyrimidine' ],
        [ 'HEU', 'pyrimidine' ],
        [ 'HN0', 'purine' ],
        [ 'HN1', 'purine' ],
        [   'I', 'purine' ],
        [ 'I4U', 'pyrimidine' ],
        [ 'I5C', 'pyrimidine' ],
        [  'IG', 'purine' ],
        [ 'IGU', 'purine' ],
        [  'IU', 'pyrimidine' ],
        [ 'J0X', 'pyrimidine' ],
        [ 'JDT', 'pyrimidine' ],
        [ 'JW5', 'pyrimidine' ],
        [ 'KAG', 'purine' ],
        [ 'LCA', 'purine' ],
        [ 'LCG', 'purine' ],
        [ 'LCH', 'pyrimidine' ],
        [ 'LGP', 'purine' ],
        [ 'LHH', 'pyrimidine' ],
        [ 'LSH', 'pyrimidine' ],
        [ 'LST', 'pyrimidine' ],
        [ 'LV2', 'pyrimidine' ],
        [ 'M1G', 'purine' ],
        [ 'M2G', 'purine' ],
        [ 'M3O', 'purine' ],
        [ 'M5M', 'pyrimidine' ],
        [ 'M7A', 'purine' ],
        [ 'MA6', 'purine' ],
        [ 'MA7', 'purine' ],
        [ 'MAD', 'purine' ],
        [ 'MDV', 'purine' ],
        [ 'MG1', 'purine' ],
        [ 'MGV', 'purine' ],
        [ 'MIA', 'purine' ],
        [ 'MMX', 'pyrimidine' ],
        [ 'MNU', 'pyrimidine' ],
        [ 'MRG', 'purine' ],
        [ 'MUM', 'pyrimidine' ],
        [ 'N4S', 'pyrimidine' ],
        [ 'N5M', 'pyrimidine' ],
        [ 'N7X', 'pyrimidine' ],
        [ 'NCX', 'purine' ],
        [ 'NDU', 'pyrimidine' ],
        [ 'NMS', 'pyrimidine' ],
        [ 'NMT', 'pyrimidine' ],
        [ 'O2G', 'purine' ],
        [ 'O2Z', 'purine' ],
        [ 'OFC', 'pyrimidine' ],
        [ 'OGX', 'purine' ],
        [ 'OHU', 'pyrimidine' ],
        [ 'OIP', 'purine' ],
        [ 'OKN', 'pyrimidine' ],
        [ 'OKT', 'pyrimidine' ],
        [ 'OMC', 'pyrimidine' ],
        [ 'OMG', 'purine' ],
        [ 'OMU', 'pyrimidine' ],
        [ 'OWR', 'purine' ],
        [   'P', 'purine' ],
        [ 'P2T', 'pyrimidine' ],
        [ 'P4U', 'pyrimidine' ],
        [ 'P5P', 'purine' ],
        [ 'PDU', 'pyrimidine' ],
        [ 'PG7', 'purine' ],
        [ 'PGN', 'purine' ],
        [ 'PGP', 'purine' ],
        [ 'PPW', 'purine' ],
        [ 'PR5', 'purine' ],
        [ 'PRN', 'purine' ],
        [ 'PST', 'pyrimidine' ],
        [ 'PYO', 'pyrimidine' ],
        [ 'QSK', 'pyrimidine' ],
        [ 'QSQ', 'purine' ],
        [ 'QUO', 'purine' ],
        [   'R', 'purine' ],
        [ 'RBD', 'purine' ],
        [ 'RDG', 'purine' ],
        [ 'RFJ', 'purine' ],
        [ 'RMP', 'purine' ],
        [ 'RPC', 'pyrimidine' ],
        [ 'RSP', 'pyrimidine' ],
        [ 'RSQ', 'pyrimidine' ],
        [  'RT', 'pyrimidine' ],
        [ 'RUS', 'pyrimidine' ],
        [  'RY', 'pyrimidine' ],
        [ 'S2M', 'pyrimidine' ],
        [ 'S4U', 'pyrimidine' ],
        [ 'S6G', 'purine' ],
        [ 'S6M', 'pyrimidine' ],
        [  'SC', 'pyrimidine' ],
        [ 'SDE', 'purine' ],
        [ 'SDG', 'purine' ],
        [ 'SDH', 'purine' ],
        [ 'SMP', 'purine' ],
        [ 'SMT', 'pyrimidine' ],
        [ 'SRA', 'purine' ],
        [ 'SSU', 'pyrimidine' ],
        [ 'SUR', 'pyrimidine' ],
        [   'T', 'pyrimidine' ],
        [ 'T0N', 'pyrimidine' ],
        [ 'T0Q', 'pyrimidine' ],
        [ 'T2S', 'pyrimidine' ],
        [ 'T31', 'pyrimidine' ],
        [ 'T36', 'pyrimidine' ],
        [ 'T38', 'pyrimidine' ],
        [ 'T39', 'pyrimidine' ],
        [ 'T41', 'pyrimidine' ],
        [ 'T5O', 'pyrimidine' ],
        [ 'T5S', 'pyrimidine' ],
        [ 'T6A', 'purine' ],
        [ 'TAF', 'pyrimidine' ],
        [ 'TC1', 'pyrimidine' ],
        [ 'TED', 'pyrimidine' ],
        [ 'TFE', 'pyrimidine' ],
        [ 'THX', 'pyrimidine' ],
        [  'TS', 'pyrimidine' ],
        [ 'TTI', 'pyrimidine' ],
        [ 'TTM', 'pyrimidine' ],
        [ 'TX2', 'pyrimidine' ],
        [   'U', 'pyrimidine' ],
        [ 'U25', 'pyrimidine' ],
        [ 'U2L', 'pyrimidine' ],
        [ 'U2N', 'pyrimidine' ],
        [ 'U31', 'pyrimidine' ],
        [ 'U37', 'pyrimidine' ],
        [ 'U48', 'pyrimidine' ],
        [ 'U7B', 'pyrimidine' ],
        [ 'U8U', 'pyrimidine' ],
        [ 'UAR', 'pyrimidine' ],
        [ 'UBI', 'pyrimidine' ],
        [ 'UBR', 'pyrimidine' ],
        [ 'UCL', 'pyrimidine' ],
        [ 'UD5', 'pyrimidine' ],
        [ 'UFB', 'pyrimidine' ],
        [ 'UFP', 'pyrimidine' ],
        [ 'UFR', 'pyrimidine' ],
        [ 'UOA', 'pyrimidine' ],
        [ 'UPE', 'pyrimidine' ],
        [ 'UPS', 'pyrimidine' ],
        [ 'UPV', 'pyrimidine' ],
        [ 'US2', 'pyrimidine' ],
        [ 'US3', 'pyrimidine' ],
        [ 'US5', 'pyrimidine' ],
        [ 'UY4', 'purine' ],
        [ 'V3L', 'purine' ],
        [ 'VC7', 'purine' ],
        [   'X', 'purine' ],
        [ 'XCY', 'pyrimidine' ],
        [ 'XFC', 'pyrimidine' ],
        [ 'XNY', 'purine' ],
        [ 'XPB', 'purine' ],
        [ 'XUA', 'purine' ],
        [   'Y', 'purine' ],
        [ 'Y5P', 'pyrimidine' ],
        [ 'YCO', 'pyrimidine' ],
        [  'YG', 'purine' ],
        [ 'YYG', 'purine' ],
        [   'Z', 'pyrimidine' ],
        [ 'ZDU', 'pyrimidine' ]
    ]);

    export const AnchorAtoms = {
        backbone: {
            first: [ "C5'", "C4'", "O4'", "C3'", "O3'", "C1'", "O4'" ],
            second: [ "P", "O5'", "C5'", "C4'", "O4'", "C3'", "O3'", "C1'", "O4'" ]
        },
        base: {
            purine: [ "N9", "C4" ],
            pyrimidine: [ "N1", "C2" ],
            'non-standard': [],
        } as Record<ResidueKind, string[]>
    };
}
