import { Report } from '../';
import { Colors } from '../colors';
import { Fonts, Tables } from '../styling';
import { Layout } from '../layout';
import { NTTable } from '../nottex/primitives';
import { NTMm, NTUnit, NTXYWH } from '../nottex/space';
import { GlobalConfig } from '../../global-config';
import { Version } from '../../version';
import '../../../../assets/imgs/definition_new_trans2.png';

async function getImage() {
    const req = await fetch(`${GlobalConfig.data().pathPrefix}/imgs/definition_new_trans2.png`);
    if (!req.ok)
        throw new Error('Cannot get title image');
    return await req.arrayBuffer();
}

export namespace Title {
    export async function add<Output>(ctx: Report.Context<Output>) {
        const imgBuf = await getImage();

        const root = ctx.ntDoc;

        // --- HEADER ---
        let inset = root.inset(
            NTXYWH.create(NTMm(0), NTMm(0), ctx.cDims.width),
            {
                backgroundColor: Colors.SectionHeaderBg
            }
        );

        // Padding of the entire inset
        const pad = Layout.insetPadding(inset.xywh, ctx);

        // Left side with text
        const leftBoxArea = { ...pad };
        leftBoxArea.width = NTUnit.multiply(0.4, leftBoxArea.width);

        const leftBox = inset.inset(leftBoxArea);
        leftBox.lineText(
            GlobalConfig.data().displayedProductName,
            { font: Fonts.ReportTitle },
            'leftBox',
        );
        leftBox.breakLine(Fonts.ReportTitle);
        leftBox.paragraphText(
            'Validation report of nucleic acid structure',
            {
                color: Colors.SectionHeaderFg,
                font: Fonts.SectionCaption,
            }
        );

        // Right side with image
        const rightBoxArea = {
            x: NTUnit.subtract(NTUnit.subtract(inset.xywh.width, leftBoxArea.width), pad.x),
            y: NTUnit.zero(),
            width: leftBoxArea.width
        };
        const rightBox = inset.inset(rightBoxArea, {}, 'leftBox');
        rightBox.image('png', imgBuf, { hAlign: 'right', scale: 0.3 });

        root.breakLine();

        // --- BASIC INFO ---
        const now = new Date();

        root.lineText(`This summary report was generated by ${GlobalConfig.data().displayedProductName} version ${Version.tag()}`);
        const tbl = root.table(2);
        tbl.addRow([
            NTTable.Cell.lineText('Date:', tbl, { font: Tables.EnumTableName.font }, Tables.EnumTableName.cell),
            NTTable.Cell.lineText(`${now.getUTCFullYear()}-${now.getUTCMonth().toString().padStart(2, '0')}-${now.getUTCDate()}`, tbl, { font: Tables.EnumTableValue.font }, Tables.EnumTableValue.cell)
        ]);
        tbl.addRow([
            NTTable.Cell.lineText('Structure ID:', tbl, { font: Tables.EnumTableName.font }, Tables.EnumTableName.cell),
            NTTable.Cell.lineText(ctx.dnatcofication.pdbId, tbl, { font: Tables.EnumTableValue.font }, Tables.EnumTableValue.cell)
        ]);
        root.breakLine();

        let url = `${ctx.href}/app/dnatco/downloads`;
        root.lineText('The full report is available at:');
        root.hyperlink(url, url);
        root.breakLine();

        if (!ctx.dnatcofication.data.isCustomStructure) {
            url = `${ctx.href}/app/dnatco/validation/confals-rmsds?cifcode=${ctx.dnatcofication.pdbId.toLowerCase()}`;
            root.lineText('Detailed table of assigned NtC classes of each dinucleotide step is available at:');
            root.hyperlink(url, url);
            root.breakLine();

            url = `${ctx.href}/app/dnatco/validation/angles-lengths?cifcode=${ctx.dnatcofication.pdbId.toLowerCase()}`;
            root.lineText('Validation of valence geometry (bond lengths and angles) is available at:');
            root.hyperlink(url, url);
            root.breakLine();
        }

        root.breakPage();
    }
}
